spring:
  application:
    name: EcommerceFrontend

  datasource:
    url: jdbc:mysql://localhost:3306/shopme
    username: root
    password: BunDau2210

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 422744014678-e8j8nnshk14011pc86bib5vb4gt34rh7.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 1294853735023508
            client-secret: c6190c309783f7054efdbfaad42c749c
            scope:
              - email
              - public_profile

server:
  port: 80
  servlet:
    context-path: /ecommerce
